name: Build

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: # 添加手动触发选项

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup xmake
      uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: latest

    - name: Build
      run: |
        xmake config -p windows -a x64 -m release
        xmake

    - name: Package
      run: |
        mkdir -p dist
        xmake install -o dist
        cp LICENSE dist/
        cp README.md dist/
        Compress-Archive -Path dist/* -DestinationPath xlog_decode-win-x64.zip

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      id: upload-win-artifact
      with:
        name: xlog_decode-win-x64
        path: xlog_decode-win-x64.zip

  build-macos-intel:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup xmake
      uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: latest

    - name: Build
      run: |
        xmake config -p macosx -a x86_64 -m release
        xmake

    - name: Package
      run: |
        mkdir -p dist
        xmake install -o dist
        cp LICENSE dist/
        cp README.md dist/
        zip -r xlog_decode-macos-x64.zip dist/*

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      id: upload-macos-intel-artifact
      with:
        name: xlog_decode-macos-x64
        path: xlog_decode-macos-x64.zip

  build-macos-arm:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup xmake
      uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: latest

    - name: Build for ARM
      run: |
        xmake config -p macosx -a arm64 -m release
        xmake

    - name: Package
      run: |
        mkdir -p dist
        xmake install -o dist
        cp LICENSE dist/
        cp README.md dist/
        zip -r xlog_decode-macos-arm64.zip dist/*

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      id: upload-macos-arm-artifact
      with:
        name: xlog_decode-macos-arm64
        path: xlog_decode-macos-arm64.zip

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup xmake
      uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: latest

    - name: Build
      run: |
        xmake config -p linux -a x86_64 -m release
        xmake

    - name: Package
      run: |
        mkdir -p dist
        xmake install -o dist
        cp LICENSE dist/
        cp README.md dist/
        zip -r xlog_decode-linux-x64.zip dist/*

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      id: upload-linux-artifact
      with:
        name: xlog_decode-linux-x64
        path: xlog_decode-linux-x64.zip

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build-windows, build-macos-intel, build-macos-arm, build-linux]
    runs-on: ubuntu-latest
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./artifacts

    - name: Create Release and Upload Assets
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./artifacts/xlog_decode-win-x64/xlog_decode-win-x64.zip
          ./artifacts/xlog_decode-macos-x64/xlog_decode-macos-x64.zip
          ./artifacts/xlog_decode-macos-arm64/xlog_decode-macos-arm64.zip
          ./artifacts/xlog_decode-linux-x64/xlog_decode-linux-x64.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}